// Datos reales de empleados con restricciones laborales - Plasticaucho Industrial
// Extraídos de: MATRIZ DE LIMITACIONES LABORALES.xlsx
// Total de empleados: 103

const empleados = [
    {
        codigo: "5938",
        nombre: "HUGO ALFREDO RAMIREZ ALTASIG",
        tipoRestriccion: "Definitiva",
        area: "MANTENIMIENTO DE PLANTAS",
        gerencia: "Ivan Alvarez",
        fechaInicio: "2014-03-10",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en MANTENIMIENTO DE PLANTAS",
        genero: "Masculino",
        edad: "40",
        puesto: "TECNICO DE MANTENIMIENTO",
        discapacidad: "No"
    },
    {
        codigo: "4815",
        nombre: "WILSON DANIEL SANTOS CHATO",
        tipoRestriccion: "Definitiva",
        area: "CALZADO INYECTADO AL CORTE",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2012-02-15",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO INYECTADO AL CORTE",
        genero: "Masculino",
        edad: "40",
        puesto: "ABASTECEDOR",
        discapacidad: "No"
    },
    {
        codigo: "2521",
        nombre: "ANGEL MANUEL TUBON PUNGUIL",
        tipoRestriccion: "Definitiva",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2004-08-17",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO CEMENTADO",
        genero: "Masculino",
        edad: "47",
        puesto: "UNTADO PEGA",
        discapacidad: "No"
    },
    {
        codigo: "2455",
        nombre: "JAIME OSWALDO ACOSTA NUÑEZ",
        tipoRestriccion: "Definitiva",
        area: "MANTENIMIENTO DE PLANTAS",
        gerencia: "Ivan Alvarez",
        fechaInicio: "2002-02-14",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en MANTENIMIENTO DE PLANTAS",
        genero: "Masculino",
        edad: "46",
        puesto: "OBRERO DE MANTENIMIENTO",
        discapacidad: "No"
    },
    {
        codigo: "3443",
        nombre: "MARIO RODOLFO GAVILANEZ UQUILLAS",
        tipoRestriccion: "Definitiva",
        area: "CALZADO INYECTADO AL CORTE",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2009-11-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO INYECTADO AL CORTE",
        genero: "Masculino",
        edad: "44",
        puesto: "BANDA DE TERMINADO",
        discapacidad: "No"
    },
    {
        codigo: "4698",
        nombre: "DAVID MAURICIO GUAMANQUISPE CHITO",
        tipoRestriccion: "Definitiva",
        area: "CALIDAD EN PLANTA",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2012-02-02",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALIDAD EN PLANTA",
        genero: "Masculino",
        edad: "35",
        puesto: "EXTRUSOR",
        discapacidad: "Física"
    },
    {
        codigo: "2755",
        nombre: "GIOVANNI ROBERTO OROZCO SORIA",
        tipoRestriccion: "Definitiva",
        area: "CALZADO MOLDEADO POR INYECCIÓN",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2007-03-15",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO MOLDEADO POR INYECCIÓN",
        genero: "Masculino",
        edad: "41",
        puesto: "AUXILIAR DE PISO",
        discapacidad: "No"
    },
    {
        codigo: "4006",
        nombre: "LUIS TIBANLOMBO POAQUIZA",
        tipoRestriccion: "Definitiva",
        area: "CALZADO INYECTADO AL CORTE",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2010-08-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO INYECTADO AL CORTE",
        genero: "Masculino",
        edad: "39",
        puesto: "TERMINADO LONA",
        discapacidad: "No"
    },
    {
        codigo: "3895",
        nombre: "EDWIN JAVIER GUERRA PUNINA",
        tipoRestriccion: "Definitiva",
        area: "CALZADO INYECTADO AL CORTE",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2010-06-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO INYECTADO AL CORTE",
        genero: "Masculino",
        edad: "46",
        puesto: "BANDA DE TERMINADO",
        discapacidad: "Auditiva"
    },
    {
        codigo: "2710",
        nombre: "DIEGO ORLANDO YANCHA PAZMIÑO",
        tipoRestriccion: "Definitiva",
        area: "CALZADO MOLDEADO POR INYECCIÓN",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2006-12-12",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO MOLDEADO POR INYECCIÓN",
        genero: "Masculino",
        edad: "42",
        puesto: "INYECTOR",
        discapacidad: "No"
    },
    {
        codigo: "5315",
        nombre: "FERNANDO GABRIEL TOAPANTA MOPOSITA",
        tipoRestriccion: "Definitiva",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2013-01-02",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO CEMENTADO",
        genero: "Masculino",
        edad: "34",
        puesto: "APARADO",
        discapacidad: "No"
    },
    {
        codigo: "6014",
        nombre: "CARLOS JAVIER SANCHEZ QUISPILLO",
        tipoRestriccion: "Definitiva",
        area: "LOGISTICA",
        gerencia: "Jose Cuesta Vasconez",
        fechaInicio: "2014-10-20",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en LOGISTICA",
        genero: "Masculino",
        edad: "39",
        puesto: "AYUDANTE LOGISTICA",
        discapacidad: "No"
    },
    {
        codigo: "2757",
        nombre: "SIXTO RAUL CASTRO MASABANDA",
        tipoRestriccion: "Definitiva",
        area: "CALZADO MOLDEADO POR INYECCIÓN",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2007-03-22",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO MOLDEADO POR INYECCIÓN",
        genero: "Masculino",
        edad: "51",
        puesto: "ABASTECEDOR DE PRODUCTO",
        discapacidad: "No"
    },
    {
        codigo: "2051",
        nombre: "SEGUNDO ALEJANDRO LLAMUCA CRIOLLO",
        tipoRestriccion: "Definitiva",
        area: "LOGISTICA",
        gerencia: "Jose Cuesta Vasconez",
        fechaInicio: "1986-04-16",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en LOGISTICA",
        genero: "Masculino",
        edad: "59",
        puesto: "AYUDANTE LOGISTICA",
        discapacidad: "39"
    },
    {
        codigo: "5397",
        nombre: "JORGE ENRIQUE MACHUCA PANIMBOZA",
        tipoRestriccion: "Definitiva",
        area: "LOGISTICA",
        gerencia: "Jose Cuesta Vasconez",
        fechaInicio: "2013-03-07",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en LOGISTICA",
        genero: "Masculino",
        edad: "35",
        puesto: "AYUDANTE LOGISTICA",
        discapacidad: "No"
    },
    {
        codigo: "2090",
        nombre: "LUIS ALFREDO LOPEZ PAREDES",
        tipoRestriccion: "Definitiva",
        area: "CALZADO MOLDEADO POR INYECCIÓN",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "1990-07-23",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO MOLDEADO POR INYECCIÓN",
        genero: "Masculino",
        edad: "59",
        puesto: "BANDA DE TERMINADO",
        discapacidad: "35"
    },
    {
        codigo: "4905",
        nombre: "JOSE VICENTE PULLUTASIG PANIMBOZA",
        tipoRestriccion: "Definitiva",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2012-04-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO CEMENTADO",
        genero: "Masculino",
        edad: "45",
        puesto: "DESTALLADOR",
        discapacidad: "No"
    },
    {
        codigo: "4024",
        nombre: "MARIA CLEMENCIA SAILEMA SAILEMA",
        tipoRestriccion: "Definitiva",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2010-09-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO CEMENTADO",
        genero: "Femenino",
        edad: "54",
        puesto: "SERVICIOS",
        discapacidad: "No"
    },
    {
        codigo: "4314",
        nombre: "JUNIOR FABRICIO SALAZAR PAUCAR",
        tipoRestriccion: "Definitiva",
        area: "CALZADO MOLDEADO POR INYECCIÓN",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2011-09-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO MOLDEADO POR INYECCIÓN",
        genero: "Masculino",
        edad: "36",
        puesto: "AUXILIAR DE PISO",
        discapacidad: "No"
    },
    {
        codigo: "4186",
        nombre: "JENRRY DAVID CARVAJAL VELASTEGUI",
        tipoRestriccion: "Definitiva",
        area: "LOGISTICA",
        gerencia: "Jose Cuesta Vasconez",
        fechaInicio: "2011-05-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en LOGISTICA",
        genero: "Masculino",
        edad: "47",
        puesto: "DESPACHADOR",
        discapacidad: "No"
    },
    {
        codigo: "2208",
        nombre: "CERVULO TARQUINO BUSTOS BUSTOS",
        tipoRestriccion: "Definitiva",
        area: "CALZADO INYECTADO AL CORTE",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "1997-05-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO INYECTADO AL CORTE",
        genero: "Masculino",
        edad: "56",
        puesto: "BANDA DE TERMINADO",
        discapacidad: "No"
    },
    {
        codigo: "4049",
        nombre: "DARWIN ROBERTO ALBAN MORALES",
        tipoRestriccion: "Definitiva",
        area: "CALZADO INYECTADO AL CORTE",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2010-10-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO INYECTADO AL CORTE",
        genero: "Masculino",
        edad: "43",
        puesto: "TERMINADO LONA",
        discapacidad: "Mental"
    },
    {
        codigo: "5452",
        nombre: "ANGEL FABIAN COLES COLES",
        tipoRestriccion: "Definitiva",
        area: "CALZADO INYECTADO AL CORTE",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2013-05-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO INYECTADO AL CORTE",
        genero: "Masculino",
        edad: "42",
        puesto: "TERMINADO LONA",
        discapacidad: "Física"
    },
    {
        codigo: "4017",
        nombre: "MARIELA ELIZABETH GUEVARA BARRIGA",
        tipoRestriccion: "Definitiva",
        area: "CALZADO INYECTADO AL CORTE",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2010-09-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO INYECTADO AL CORTE",
        genero: "Femenino",
        edad: "45",
        puesto: "TERMINADO LONA",
        discapacidad: "Auditiva"
    },
    {
        codigo: "4780",
        nombre: "EDGAR SANTIAGO LOPEZ AINAGUANO",
        tipoRestriccion: "Definitiva",
        area: "CALZADO MOLDEADO POR INYECCIÓN",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2012-02-15",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO MOLDEADO POR INYECCIÓN",
        genero: "Masculino",
        edad: "41",
        puesto: "BANDA DE TERMINADO",
        discapacidad: "Física"
    },
    {
        codigo: "4018",
        nombre: "CELINDA DOLORES MARIÑO PALACIOS",
        tipoRestriccion: "Definitiva",
        area: "CALZADO INYECTADO AL CORTE",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2010-09-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO INYECTADO AL CORTE",
        genero: "Femenino",
        edad: "42",
        puesto: "TERMINADO LONA",
        discapacidad: "Auditiva"
    },
    {
        codigo: "4118",
        nombre: "DIEGO GEOVANNY SATUQUINGA SANIPATIN",
        tipoRestriccion: "Definitiva",
        area: "CALZADO INYECTADO AL CORTE",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2010-12-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO INYECTADO AL CORTE",
        genero: "Masculino",
        edad: "35",
        puesto: "OBRERO DE MANTENIMIENTO",
        discapacidad: "Física"
    },
    {
        codigo: "4692",
        nombre: "ORLANDO RAMIRO PEÑA SAILEMA",
        tipoRestriccion: "Definitiva",
        area: "CALZADO INYECTADO AL CORTE",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2012-02-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO INYECTADO AL CORTE",
        genero: "Masculino",
        edad: "41",
        puesto: "TERMINADO LONA",
        discapacidad: "Intelectual"
    },
    {
        codigo: "4085",
        nombre: "VICTOR MIGUEL PAZMIÑO BONILLA",
        tipoRestriccion: "Definitiva",
        area: "CALZADO MOLDEADO POR INYECCIÓN",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2010-11-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO MOLDEADO POR INYECCIÓN",
        genero: "Masculino",
        edad: "55",
        puesto: "TERMINADO PLASTICO",
        discapacidad: "Visual"
    },
    {
        codigo: "2452",
        nombre: "WALTER VINICIO JAQUE MANOBANDA",
        tipoRestriccion: "Definitiva",
        area: "CALZADO INYECTADO AL CORTE",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2002-01-28",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO INYECTADO AL CORTE",
        genero: "Masculino",
        edad: "44",
        puesto: "INYECTOR",
        discapacidad: "No"
    },
    {
        codigo: "2195",
        nombre: "JORGE ALCIBAR POVEDA PAZMIÑO",
        tipoRestriccion: "Definitiva",
        area: "CALZADO INYECTADO AL CORTE",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "1997-03-04",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO INYECTADO AL CORTE",
        genero: "Masculino",
        edad: "53",
        puesto: "INYECTOR",
        discapacidad: "No"
    },
    {
        codigo: "2115",
        nombre: "SEGUNDO FRANCISCO PALATE PALATE",
        tipoRestriccion: "Definitiva",
        area: "CALZADO MOLDEADO POR INYECCIÓN",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "1991-04-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO MOLDEADO POR INYECCIÓN",
        genero: "Masculino",
        edad: "59",
        puesto: "BANDA DE TERMINADO",
        discapacidad: "No"
    },
    {
        codigo: "2418",
        nombre: "WILMER ROBERTO VILLACIS MAYORGA",
        tipoRestriccion: "Definitiva",
        area: "CALZADO MOLDEADO POR INYECCIÓN",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2001-08-17",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO MOLDEADO POR INYECCIÓN",
        genero: "Masculino",
        edad: "51",
        puesto: "ABASTECEDOR DE PRODUCTO",
        discapacidad: "No"
    },
    {
        codigo: "2276",
        nombre: "JUAN SANTIAGO PEREZ GUZMAN",
        tipoRestriccion: "Definitiva",
        area: "LOGISTICA",
        gerencia: "Jose Cuesta Vasconez",
        fechaInicio: "2000-02-14",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en LOGISTICA",
        genero: "Masculino",
        edad: "52",
        puesto: "AYUDANTE LOGISTICA",
        discapacidad: "No"
    },
    {
        codigo: "3005",
        nombre: "RICARDO DAVID ACURIO SANCHEZ",
        tipoRestriccion: "Definitiva",
        area: "CALZADO MOLDEADO POR INYECCIÓN",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2007-10-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO MOLDEADO POR INYECCIÓN",
        genero: "Masculino",
        edad: "38",
        puesto: "AUXILIAR DE PISO",
        discapacidad: "No"
    },
    {
        codigo: "3559",
        nombre: "FLAVIO DAVID PILATAGSI CAIZA",
        tipoRestriccion: "Definitiva",
        area: "CALZADO MOLDEADO POR INYECCIÓN",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2010-01-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO MOLDEADO POR INYECCIÓN",
        genero: "Masculino",
        edad: "36",
        puesto: "ALIMENTADOR DE BANDA",
        discapacidad: "No"
    },
    {
        codigo: "4956",
        nombre: "PEDRO PABLO PLACENCIA GUAMANCURI",
        tipoRestriccion: "Definitiva",
        area: "LOGISTICA",
        gerencia: "Jose Cuesta Vasconez",
        fechaInicio: "2012-06-20",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en LOGISTICA",
        genero: "Masculino",
        edad: "40",
        puesto: "AYUDANTE LOGISTICA",
        discapacidad: "Auditiva"
    },
    {
        codigo: "3901",
        nombre: "GALO JAVIER CURAY SUPE",
        tipoRestriccion: "Definitiva",
        area: "LOGISTICA",
        gerencia: "Jose Cuesta Vasconez",
        fechaInicio: "2010-06-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en LOGISTICA",
        genero: "Masculino",
        edad: "39",
        puesto: "AYUDANTE LOGISTICA",
        discapacidad: "Visual"
    },
    {
        codigo: "5896",
        nombre: "MARCOS ANDRES MENDOZA LORENTY",
        tipoRestriccion: "Definitiva",
        area: "LOGISTICA",
        gerencia: "Jose Cuesta Vasconez",
        fechaInicio: "2014-01-23",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en LOGISTICA",
        genero: "Masculino",
        edad: "42",
        puesto: "AYUDANTE LOGISTICA",
        discapacidad: "No"
    },
    {
        codigo: "2175",
        nombre: "MILTON ISOLIANO ZAMBRANO MOLINA",
        tipoRestriccion: "Definitiva",
        area: "CALZADO MOLDEADO POR INYECCIÓN",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "1996-06-05",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO MOLDEADO POR INYECCIÓN",
        genero: "Masculino",
        edad: "60",
        puesto: "OBRERO DE MANTENIMIENTO",
        discapacidad: "No"
    },
    {
        codigo: "2415",
        nombre: "DARWIN GIOVANNI SANTOS CHATO",
        tipoRestriccion: "Definitiva",
        area: "CALZADO MOLDEADO POR INYECCIÓN",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2001-08-03",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO MOLDEADO POR INYECCIÓN",
        genero: "Masculino",
        edad: "49",
        puesto: "OBRERO DE MANTENIMIENTO",
        discapacidad: "No"
    },
    {
        codigo: "6681",
        nombre: "EDISSON ROBERTO CHANGO LAURA",
        tipoRestriccion: "Definitiva",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2019-12-23",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO CEMENTADO",
        genero: "Masculino",
        edad: "31",
        puesto: "OBRERO PISA",
        discapacidad: "No"
    },
    {
        codigo: "5352",
        nombre: "JAIME ARTURO BOSQUE CHICO",
        tipoRestriccion: "Definitiva",
        area: "CALZADO CEMENTADO",
        gerencia: "Ivan Alvarez",
        fechaInicio: "2013-02-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO CEMENTADO",
        genero: "Masculino",
        edad: "45",
        puesto: "OBRERO",
        discapacidad: "No"
    },
    {
        codigo: "4772",
        nombre: "PABLO ENRIQUE LASCANO ANDALUZ",
        tipoRestriccion: "Definitiva",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2012-02-15",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO CEMENTADO",
        genero: "Masculino",
        edad: "51",
        puesto: "LIDER A",
        discapacidad: "Visual"
    },
    {
        codigo: "5690",
        nombre: "SANTIAGO JAVIER PAZMIÑO LOPEZ",
        tipoRestriccion: "Definitiva",
        area: "CALZADO INYECTADO AL CORTE",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2013-07-22",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO INYECTADO AL CORTE",
        genero: "Masculino",
        edad: "40",
        puesto: "INYECTOR",
        discapacidad: "No"
    },
    {
        codigo: "2308",
        nombre: "PATRICIO VLADIMIR LEDESMA CHAVEZ",
        tipoRestriccion: "Definitiva",
        area: "MEZCLAS TERMOPLASTICAS",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2000-11-06",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en MEZCLAS TERMOPLASTICAS",
        genero: "Masculino",
        edad: "52",
        puesto: "EXTRUSOR",
        discapacidad: "No"
    },
    {
        codigo: "3870",
        nombre: "HERNAN ROBERTO VILLACIS VILLACIS",
        tipoRestriccion: "Definitiva",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2010-04-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO CEMENTADO",
        genero: "Masculino",
        edad: "53",
        puesto: "OBRERO PISA",
        discapacidad: "Física"
    },
    {
        codigo: "4914",
        nombre: "ANGEL DIONISIO LASCANO CRUZ",
        tipoRestriccion: "Definitiva",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2012-04-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO CEMENTADO",
        genero: "Masculino",
        edad: "59",
        puesto: "OBRERO PISA",
        discapacidad: "Física"
    },
    {
        codigo: "2470",
        nombre: "FERNANDO SANTIAGO MAYORGA ALDAZ",
        tipoRestriccion: "Definitiva",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2002-07-17",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO CEMENTADO",
        genero: "Masculino",
        edad: "44",
        puesto: "OBRERO PISA",
        discapacidad: "Auditiva"
    },
    {
        codigo: "3121",
        nombre: "DARWIN NEPTALI TUBON QUISHPE",
        tipoRestriccion: "Definitiva",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2008-12-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO CEMENTADO",
        genero: "Masculino",
        edad: "40",
        puesto: "OBRERO PISA",
        discapacidad: "Auditiva"
    },
    {
        codigo: "3899",
        nombre: "ANA GABRIELA SOLIS SOLIS",
        tipoRestriccion: "Definitiva",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2010-06-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO CEMENTADO",
        genero: "Femenino",
        edad: "36",
        puesto: "OBRERO PISA",
        discapacidad: "Auditiva"
    },
    {
        codigo: "5564",
        nombre: "EMILIO BERNARDO FREIRE VILLEGAS",
        tipoRestriccion: "Definitiva",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2013-06-17",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO CEMENTADO",
        genero: "Masculino",
        edad: "40",
        puesto: "OBRERO PISA",
        discapacidad: "Física"
    },
    {
        codigo: "3164",
        nombre: "JUAN ELIAS ESPIN ESPIN",
        tipoRestriccion: "Definitiva",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2009-05-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO CEMENTADO",
        genero: "Masculino",
        edad: "58",
        puesto: "OBRERO PISA",
        discapacidad: "Auditiva"
    },
    {
        codigo: "4696",
        nombre: "MARIA VERONICA TORRES MOYANO",
        tipoRestriccion: "Definitiva",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2012-02-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO CEMENTADO",
        genero: "Femenino",
        edad: "45",
        puesto: "OBRERO PISA",
        discapacidad: "Auditiva"
    },
    {
        codigo: "5345",
        nombre: "ALEX JAVIER POAQUIZA TACOAMAN",
        tipoRestriccion: "Definitiva",
        area: "CENTRO SERVICIOS COMPARTIDOS",
        gerencia: "Ivan Alvarez",
        fechaInicio: "2013-01-24",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CENTRO SERVICIOS COMPARTIDOS",
        genero: "Masculino",
        edad: "35",
        puesto: "OBRERO DE MANTENIMIENTO",
        discapacidad: "Física"
    },
    {
        codigo: "4890",
        nombre: "MARIO CIRO ALLAUCA MUÑOZ",
        tipoRestriccion: "Definitiva",
        area: "CALZADO MOLDEADO POR INYECCIÓN",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2012-04-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO MOLDEADO POR INYECCIÓN",
        genero: "Masculino",
        edad: "60",
        puesto: "REFILADO",
        discapacidad: "Auditiva"
    },
    {
        codigo: "5571",
        nombre: "MICHAEL NAIME MENDOZA RUIZ",
        tipoRestriccion: "Definitiva",
        area: "LOGISTICA",
        gerencia: "Jose Cuesta Vasconez",
        fechaInicio: "2013-06-17",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en LOGISTICA",
        genero: "Masculino",
        edad: "38",
        puesto: "AYUDANTE LOGISTICA",
        discapacidad: "No"
    },
    {
        codigo: "4498",
        nombre: "MARIA ESPERANZA MAIZANCHO TOAPANTA",
        tipoRestriccion: "Definitiva",
        area: "CALZADO MOLDEADO POR INYECCIÓN",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2011-10-25",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO MOLDEADO POR INYECCIÓN",
        genero: "Femenino",
        edad: "43",
        puesto: "REBABEO",
        discapacidad: "Visual"
    },
    {
        codigo: "5431",
        nombre: "EDISON SANTIAGO SORIA IZA",
        tipoRestriccion: "Definitiva",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2013-05-02",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO CEMENTADO",
        genero: "Masculino",
        edad: "36",
        puesto: "OBRERO PISA",
        discapacidad: "No"
    },
    {
        codigo: "2428",
        nombre: "MARCO ANTONIO BEJARANO LLAMUCA",
        tipoRestriccion: "Definitiva",
        area: "MANTENIMIENTO DE PLANTAS",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2001-09-28",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en MANTENIMIENTO DE PLANTAS",
        genero: "Masculino",
        edad: "49",
        puesto: "OBRERO DE MANTENIMIENTO",
        discapacidad: "No"
    },
    {
        codigo: "6473",
        nombre: "STALIN EDUARDO TUBON LOPEZ",
        tipoRestriccion: "Definitiva",
        area: "LOGISTICA",
        gerencia: "Jose Cuesta Vasconez",
        fechaInicio: "2018-04-02",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en LOGISTICA",
        genero: "Masculino",
        edad: "29",
        puesto: "OBRERO",
        discapacidad: "No"
    },
    {
        codigo: "4323",
        nombre: "JOSE DARIO CAISA YUCAILLA",
        tipoRestriccion: "Definitiva",
        area: "INDUSTRIAS DIVERSAS",
        gerencia: "Ivan Alvarez",
        fechaInicio: "2011-04-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en INDUSTRIAS DIVERSAS",
        genero: "Masculino",
        edad: "42",
        puesto: "OBRERO PISA",
        discapacidad: "No"
    },
    {
        codigo: "7231",
        nombre: "LIGIA ELENA SUPE PALATE",
        tipoRestriccion: "Definitiva",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2022-12-19",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO CEMENTADO",
        genero: "Femenino",
        edad: "42",
        puesto: "OBRERO PISA",
        discapacidad: "No"
    },
    {
        codigo: "4984",
        nombre: "LUZ ANGELICA SUPE PALATE",
        tipoRestriccion: "Definitiva",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2012-07-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO CEMENTADO",
        genero: "Femenino",
        edad: "47",
        puesto: "OBRERO PISA",
        discapacidad: "No"
    },
    {
        codigo: "4878",
        nombre: "VERONICA ELIZABETH MOROCHO ESPINOZA",
        tipoRestriccion: "Definitiva",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2012-04-09",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO CEMENTADO",
        genero: "Femenino",
        edad: "38",
        puesto: "OBRERO PISA",
        discapacidad: "Visual"
    },
    {
        codigo: "3100",
        nombre: "CARLOS ANDRES SOLARTE ROSERO",
        tipoRestriccion: "Definitiva",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2008-09-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO CEMENTADO",
        genero: "Masculino",
        edad: "43",
        puesto: "OBRERO PISA",
        discapacidad: "Visual"
    },
    {
        codigo: "4678",
        nombre: "MIGUEL EDUARDO AGUILAR AMBI",
        tipoRestriccion: "Definitiva",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2012-02-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO CEMENTADO",
        genero: "Masculino",
        edad: "58",
        puesto: "OBRERO PISA",
        discapacidad: "Física"
    },
    {
        codigo: "5253",
        nombre: "IDALIA PATRICIA DIAZ SACA",
        tipoRestriccion: "Definitiva",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2012-11-19",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO CEMENTADO",
        genero: "Femenino",
        edad: "43",
        puesto: "OBRERO PISA",
        discapacidad: "No"
    },
    {
        codigo: "7195",
        nombre: "DARIO XAVIER BONILLA TIPAN",
        tipoRestriccion: "Temporal",
        area: "CALZADO INYECTADO AL CORTE",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2022-11-22",
        fechaFin: "2025-06-30",
        diagnostico: "Restricción laboral - Temporal",
        restricciones: "Empleado con limitación temporal en CALZADO INYECTADO AL CORTE",
        genero: "Masculino",
        edad: "32",
        puesto: "OBRERO PISA",
        discapacidad: "No"
    },
    {
        codigo: "4255",
        nombre: "DIEGO VINICIO REYES VACA",
        tipoRestriccion: "Definitiva",
        area: "CALIDAD EN PLANTA",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2011-07-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALIDAD EN PLANTA",
        genero: "Masculino",
        edad: "37",
        puesto: "VERIFICADOR",
        discapacidad: "No"
    },
    {
        codigo: "2157",
        nombre: "EDISON DANILO ESPIN PROAÑO",
        tipoRestriccion: "Definitiva",
        area: "METROLOGIA",
        gerencia: "Ivan Alvarez",
        fechaInicio: "1995-07-05",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en METROLOGIA",
        genero: "Masculino",
        edad: "52",
        puesto: "METROLOGIA",
        discapacidad: "No"
    },
    {
        codigo: "4549",
        nombre: "ROBERTO ANTONIO CORDOVA SANTAFE",
        tipoRestriccion: "Definitiva",
        area: "MANTENIMIENTO DE PLANTAS",
        gerencia: "Ivan Alvarez",
        fechaInicio: "2011-11-16",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en MANTENIMIENTO DE PLANTAS",
        genero: "Masculino",
        edad: "37",
        puesto: "TECNICO DE MANTENIMIENTO",
        discapacidad: "No"
    },
    {
        codigo: "2221",
        nombre: "ALONSO AGUAYO ASTUDILLO",
        tipoRestriccion: "Definitiva",
        area: "LOGISTICA",
        gerencia: "Jose Cuesta Vasconez",
        fechaInicio: "1997-07-24",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en LOGISTICA",
        genero: "Masculino",
        edad: "54",
        puesto: "No especificado",
        discapacidad: "No"
    },
    {
        codigo: "7394",
        nombre: "PATRICIO GERMAN CONSTANTE LOPEZ",
        tipoRestriccion: "Temporal",
        area: "CALZADO MOLDEADO POR INYECCIÓN",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2023-03-06",
        fechaFin: "2025-06-30",
        diagnostico: "Restricción laboral - Temporal",
        restricciones: "Empleado con limitación temporal en CALZADO MOLDEADO POR INYECCIÓN",
        genero: "Masculino",
        edad: "25",
        puesto: "OBRERO PISA",
        discapacidad: "No"
    },
    {
        codigo: "2102",
        nombre: "LUIS MARCIAL LARA LARA",
        tipoRestriccion: "Definitiva",
        area: "CALZADO MOLDEADO POR INYECCIÓN",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "1991-01-14",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO MOLDEADO POR INYECCIÓN",
        genero: "Masculino",
        edad: "59",
        puesto: "OBRERO INYECTOR",
        discapacidad: "No"
    },
    {
        codigo: "2644",
        nombre: "RAMIRO IVAN POZO JACOME",
        tipoRestriccion: "Definitiva",
        area: "LOGISTICA",
        gerencia: "Jose Cuesta Vasconez",
        fechaInicio: "2006-06-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en LOGISTICA",
        genero: "Masculino",
        edad: "41",
        puesto: "AYUDANTE LOGISTICO",
        discapacidad: "No"
    },
    {
        codigo: "5405",
        nombre: "ANDRES EDUARDO VALENCIA VAQUERO",
        tipoRestriccion: "Definitiva",
        area: "MANTENIMIENTO DE PLANTAS",
        gerencia: "Ivan Alvarez",
        fechaInicio: "2013-03-15",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en MANTENIMIENTO DE PLANTAS",
        genero: "Masculino",
        edad: "32",
        puesto: "OBRERO MANTENIMIENTO",
        discapacidad: "No"
    },
    {
        codigo: "2560",
        nombre: "FABIAN ESTALINO CULQUI COCHA",
        tipoRestriccion: "Definitiva",
        area: "INDUSTRIAS DIVERSAS",
        gerencia: "Ivan Alvarez",
        fechaInicio: "2005-04-15",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en INDUSTRIAS DIVERSAS",
        genero: "Masculino",
        edad: "43",
        puesto: "Obrero Molinero Calandrador CAUCHO",
        discapacidad: "No"
    },
    {
        codigo: "4031",
        nombre: "LUIS GIOVANNI VILLACIS DE LA CRUZ",
        tipoRestriccion: "Definitiva",
        area: "INDUSTRIAS DIVERSAS",
        gerencia: "Ivan Alvarez",
        fechaInicio: "2010-10-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en INDUSTRIAS DIVERSAS",
        genero: "Masculino",
        edad: "34",
        puesto: "OBRERO",
        discapacidad: "No"
    },
    {
        codigo: "2119",
        nombre: "LUIS ISRAEL CAMINO PAZMIÑO",
        tipoRestriccion: "Definitiva",
        area: "INDUSTRIAS DIVERSAS",
        gerencia: "Ivan Alvarez",
        fechaInicio: "1991-06-03",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en INDUSTRIAS DIVERSAS",
        genero: "Masculino",
        edad: "59",
        puesto: "LIDER A",
        discapacidad: "No"
    },
    {
        codigo: "5440",
        nombre: "ANTONIO GILBERTO MATZABALIN MORETA",
        tipoRestriccion: "Definitiva",
        area: "MEZCLAS TERMOPLASTICAS",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2013-05-13",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en MEZCLAS TERMOPLASTICAS",
        genero: "Masculino",
        edad: "36",
        puesto: "EXTRUSOR",
        discapacidad: "No"
    },
    {
        codigo: "2544",
        nombre: "SEGUNDO CARLOS ACHACHI PULLUTAGSI",
        tipoRestriccion: "Definitiva",
        area: "LOGISTICA",
        gerencia: "Jose Cuesta Vasconez",
        fechaInicio: "2005-04-01",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en LOGISTICA",
        genero: "Masculino",
        edad: "49",
        puesto: "ELEVADORISTA",
        discapacidad: "No"
    },
    {
        codigo: "5186",
        nombre: "LUIS GILBERTO TORRES PALATE",
        tipoRestriccion: "Definitiva",
        area: "DISEÑO",
        gerencia: "Patricio Toro",
        fechaInicio: "2012-10-22",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en DISEÑO",
        genero: "Masculino",
        edad: "43",
        puesto: "OPERADOR PROTOTIPO",
        discapacidad: "No"
    },
    {
        codigo: "2083",
        nombre: "LUIS RODRIGO LUIZA GUANGASI",
        tipoRestriccion: "Definitiva",
        area: "LOGISTICA",
        gerencia: "Jose Cuesta Vasconez",
        fechaInicio: "1990-06-04",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en LOGISTICA",
        genero: "Masculino",
        edad: "59",
        puesto: "AYUDANTE LOGISTICO",
        discapacidad: "No"
    },
    {
        codigo: "3087",
        nombre: "FAUSTO ISMAEL MALLIQUINGA CEVALLOS",
        tipoRestriccion: "Temporal",
        area: "CALZADO MOLDEADO POR INYECCIÓN",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2008-11-12",
        fechaFin: "2025-06-30",
        diagnostico: "Restricción laboral - Temporal",
        restricciones: "Empleado con limitación temporal en CALZADO MOLDEADO POR INYECCIÓN",
        genero: "Masculino",
        edad: "41",
        puesto: "OBRERO EMPAQUE",
        discapacidad: "No"
    },
    {
        codigo: "2238",
        nombre: "EDGAR GERMAN MOYA LOPEZ",
        tipoRestriccion: "Definitiva",
        area: "CALZADO MOLDEADO POR INYECCIÓN",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "1999-02-23",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO MOLDEADO POR INYECCIÓN",
        genero: "Masculino",
        edad: "52",
        puesto: "OBRERO EMPAQUE",
        discapacidad: "No"
    },
    {
        codigo: "2540",
        nombre: "STALIN ROBERTO ESPIN PROAÑO",
        tipoRestriccion: "Temporal",
        area: "COSTOS Y PRESUPUESTOS",
        gerencia: "Andres Cisneros",
        fechaInicio: "2005-01-12",
        fechaFin: "2025-06-30",
        diagnostico: "Restricción laboral - Temporal",
        restricciones: "Empleado con limitación temporal en COSTOS Y PRESUPUESTOS",
        genero: "Masculino",
        edad: "47",
        puesto: "ANALISTA PROCESOS",
        discapacidad: "No"
    },
    {
        codigo: "4439",
        nombre: "MARCO FABRICIO VILLAMAR ESCALANTE",
        tipoRestriccion: "Temporal",
        area: "LOGISTICA",
        gerencia: "Jose Cuesta Vasconez",
        fechaInicio: "2011-09-01",
        fechaFin: "2025-06-30",
        diagnostico: "Restricción laboral - Temporal",
        restricciones: "Empleado con limitación temporal en LOGISTICA",
        genero: "Masculino",
        edad: "44",
        puesto: "AYUDANTE LOGISTICA",
        discapacidad: "No"
    },
    {
        codigo: "6919",
        nombre: "GUADALUPE DEL PILAR TOAPANTA MANOBANDA",
        tipoRestriccion: "Temporal",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2022-05-19",
        fechaFin: "2025-06-30",
        diagnostico: "Restricción laboral - Temporal",
        restricciones: "Empleado con limitación temporal en CALZADO CEMENTADO",
        genero: "Femenino",
        edad: "32",
        puesto: "OBRERO PISA",
        discapacidad: "No"
    },
    {
        codigo: "2520",
        nombre: "VICTOR HUGO VILLACIS MIÑO",
        tipoRestriccion: "Definitiva",
        area: "LOGISTICA",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2004-08-17",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en LOGISTICA",
        genero: "Masculino",
        edad: "46",
        puesto: "OBRERO MOD",
        discapacidad: "No"
    },
    {
        codigo: "7414",
        nombre: "JUAN CARLOS LARA FREIRE",
        tipoRestriccion: "Definitiva",
        area: "MANTENIMIENTO DE PLANTAS",
        gerencia: "Ivan Alvarez",
        fechaInicio: "2023-03-17",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en MANTENIMIENTO DE PLANTAS",
        genero: "Masculino",
        edad: "33",
        puesto: "TECNICO DE MANTENIMIENTO",
        discapacidad: "No"
    },
    {
        codigo: "6991",
        nombre: "SILVANA SOLEDAD SAILEMA SAILEMA",
        tipoRestriccion: "Temporal",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2022-06-13",
        fechaFin: "2025-06-30",
        diagnostico: "Restricción laboral - Temporal",
        restricciones: "Empleado con limitación temporal en CALZADO CEMENTADO",
        genero: "Femenino",
        edad: "31",
        puesto: "OBRERO PISA",
        discapacidad: "No"
    },
    {
        codigo: "7098",
        nombre: "CHRISTIAN FERNANDO QUINATOA TIBAN",
        tipoRestriccion: "Temporal",
        area: "LOGISTICA",
        gerencia: "Jose Cuesta Vasconez",
        fechaInicio: "2022-08-23",
        fechaFin: "2025-06-30",
        diagnostico: "Restricción laboral - Temporal",
        restricciones: "Empleado con limitación temporal en LOGISTICA",
        genero: "Masculino",
        edad: "28",
        puesto: "AYUDANTE LOGISTICO",
        discapacidad: "No"
    },
    {
        codigo: "6977",
        nombre: "WILMER DAVID DUCHICELA QUINLLE",
        tipoRestriccion: "Definitiva",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2022-06-07",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO CEMENTADO",
        genero: "Masculino",
        edad: "36",
        puesto: "TROQUELADOR",
        discapacidad: "No"
    },
    {
        codigo: "7010",
        nombre: "YADIRA MICAELA PALATE ULLAURI",
        tipoRestriccion: "Temporal",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2022-07-01",
        fechaFin: "2025-06-30",
        diagnostico: "Restricción laboral - Temporal",
        restricciones: "Empleado con limitación temporal en CALZADO CEMENTADO",
        genero: "Femenino",
        edad: "30",
        puesto: "OBRERO PISA",
        discapacidad: "No"
    },
    {
        codigo: "6721",
        nombre: "CHRISTIAN ALEXIS SALAZAR BUENAÑO",
        tipoRestriccion: "Temporal",
        area: "LOGISTICA",
        gerencia: "Jose Cuesta Vasconez",
        fechaInicio: "2022-03-25",
        fechaFin: "2025-06-30",
        diagnostico: "Restricción laboral - Temporal",
        restricciones: "Empleado con limitación temporal en LOGISTICA",
        genero: "Masculino",
        edad: "32",
        puesto: "AYUDANTE LOGISTICO",
        discapacidad: "No"
    },
    {
        codigo: "7241",
        nombre: "JOFFRE ALEXANDER ERAS LANDA",
        tipoRestriccion: "Temporal",
        area: "MATRICERIA",
        gerencia: "Ivan Alvarez",
        fechaInicio: "2022-12-20",
        fechaFin: "2025-06-30",
        diagnostico: "Restricción laboral - Temporal",
        restricciones: "Empleado con limitación temporal en MATRICERIA",
        genero: "Masculino",
        edad: "24",
        puesto: "MATRICERO 1",
        discapacidad: "No"
    },
    {
        codigo: "5620",
        nombre: "WILSON LIZANDRO ALVARADO OLMEDO",
        tipoRestriccion: "Temporal",
        area: "LOGISTICA",
        gerencia: "Jose Cuesta Vasconez",
        fechaInicio: "2013-07-08",
        fechaFin: "2025-06-30",
        diagnostico: "Restricción laboral - Temporal",
        restricciones: "Empleado con limitación temporal en LOGISTICA",
        genero: "Masculino",
        edad: "37",
        puesto: "AYUDANTE LOGISTICA",
        discapacidad: "No"
    },
    {
        codigo: "2858",
        nombre: "MARCELO VINICIO COCHA MEDINA",
        tipoRestriccion: "Definitiva",
        area: "MEZCLAS TERMOPLASTICAS",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2007-06-04",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en MEZCLAS TERMOPLASTICAS",
        genero: "Masculino",
        edad: "45",
        puesto: "OBRERO PISA",
        discapacidad: "No"
    },
    {
        codigo: "4571",
        nombre: "WALTER JONNY VARGAS GUAMAN",
        tipoRestriccion: "Definitiva",
        area: "CALZADO CEMENTADO",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2011-11-21",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en CALZADO CEMENTADO",
        genero: "Masculino",
        edad: "55",
        puesto: "APARADO AUTOMATAS",
        discapacidad: "No"
    },
    {
        codigo: "6257",
        nombre: "JUAN FERNANDO GUEVARA GUZMAN",
        tipoRestriccion: "Definitiva",
        area: "SERVICIOS INDUSTRIALES",
        gerencia: "Ivan Alvarez",
        fechaInicio: "2015-10-26",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en SERVICIOS INDUSTRIALES",
        genero: "Masculino",
        edad: "36",
        puesto: "TECNICO DE MANTENIMIENTO",
        discapacidad: "No"
    },
    {
        codigo: "2318",
        nombre: "GALO NEPTALI ACURIO MEDINA",
        tipoRestriccion: "Definitiva",
        area: "MANTENIMIENTO DE PLANTAS",
        gerencia: "Ivan Alvarez",
        fechaInicio: "2000-11-27",
        fechaFin: null,
        diagnostico: "Restricción laboral - Definitiva",
        restricciones: "Empleado con limitación definitiva en MANTENIMIENTO DE PLANTAS",
        genero: "Masculino",
        edad: "49",
        puesto: "TECNICO DE MANTENIMIENTO",
        discapacidad: "No"
    },
    {
        codigo: "4780",
        nombre: "EDGAR SANTIAGO LOPEZ AINAGUANO",
        tipoRestriccion: "Temporal",
        area: "CALIDAD EN PLANTA",
        gerencia: "Juan Ignacio Sevilla",
        fechaInicio: "2012-02-15",
        fechaFin: "2025-06-30",
        diagnostico: "Restricción laboral - Temporal",
        restricciones: "Empleado con limitación temporal en CALIDAD EN PLANTA",
        genero: "Masculino",
        edad: "41",
        puesto: "SUPERVISOR CALDIAD",
        discapacidad: "Física"
    }
];

// Exportar datos
window.empleadosData = empleados;
